# Generated by Django 4.2.6 on 2023-10-13 20:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies_orders', '0001_initial'),
        ('movies', '0004_alter_movie_duration_alter_movie_synopsis'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='orders',
            field=models.ManyToManyField(related_name='movies_orders', through='movies_orders.MovieOrder', to=settings.AUTH_USER_MODEL),
        ),
    ]
